# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       rfkill

# >> macros
# << macros

Summary:    Tool for setting the rfkill switch setting
Version:    0.4
Release:    1.1.1
Group:      System/Base
License:    ISC
URL:        http://wireless.kernel.org/en/users/Documentation/rfkill
Source0:    rfkill.c
Source1:    rfkill.h
Source2:    core.h
Source100:  rfkill.yaml

%description
With this tool the rfkill setting for network, bluetooth, etc. interfaces can be set.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_sbindir}/%{name}
%{_mandir}/man8/%{name}.8.gz
# >> files
# << files
%changelog
* Sat Mar 30 2013 Ruediger Gad <r.c.g@gmx.de> - 0.4
- Improve packaging.
* Thu Dec 27 2012 Ruediger Gad <r.c.g@gmx.de> - 0.4
- First version for Mer.
